name: Reckoner
description: "Run a reckoner command"

inputs:
  reckoner-command:
    description: "reckoner command"
    required: true
    default: "reckoner --help"

outputs:
  time:
    description: "The time "

runs:
  using: docker
  # image: Dockerfile
  image: "docker://public.ecr.aws/i9h4d0i0/apex-crypto/reckoner-action:v2" # pinned image to speedup the action
  args:
    - ${{ inputs.reckoner-command }}
